### ISSUE TITLE
Error: Compendium 1000 Fish is configured for an invalid Entity type RollableTable on Foundry 0.7.1

### ISSUE THREAD

**Issue by p4535992** [cswendrowski/FoundryVTT-1000-Fish#1]
**Environment Details:**

Foundry VTT Version: 0.7.1
Operating System: [Linux]
How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.95
Modules Enabled?: Yes

**Description of the issue:**

After install the module i have started my world and go to "Module Settings" for enable the module, but i get the following error message "Error: Compendium 1000 Fish is configured for an invalid Entity type RollableTable".

**Comment by cswendrowski** [comment]
@p4535992 this should be fixed in v1.0.1

**Comment by p4535992** [comment]
Confirmed it's work !! ty.
